### ISSUE TITLE
Upgrade to latest brain.js

### ISSUE THREAD

**Issue by robertleeplummerjr** [primaryobjects/nnsorting#1]
This would be an interesting example as well.

**Comment by robertleeplummerjr** [comment]
So that is... no?

**Comment by primaryobjects** [comment]
Please feel free to fork or submit a PR. Thanks!

**Comment by robertleeplummerjr** [comment]
ok cool.  Ty!

**Comment by primaryobjects** [comment]
Replaced brain with [brain.js](https://www.npmjs.com/package/brain.js) https://github.com/primaryobjects/nnsorting/commit/5270d8a39124997f37814cc4d67b8de6f38de6ca

**Comment by robertleeplummerjr** [comment]
Rock on!
